# dynamic_title = true
general.import = ["/Users/jorgealves/.config/alacritty/fonts.toml"]

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true

[window.padding]
x = 0
y = 0
