--require("main.plugins.settings.nvimtree")
-- require("main.plugins.settings.autopairs")
-- require("main.plugins.settings.autosave")
require("main.plugins.settings.comment")
require("main.plugins.settings.gitsigns")
require("main.plugins.settings.toggleterm")
require("main.plugins.settings.whichkey")
-- require("main.plugins.settings.lualine")
-- require("main.plugins.settings.bufferline")
require("main.plugins.settings.treesitter")
require("main.plugins.settings.lsp")
require("main.plugins.settings.cmp")
require('main.plugins.settings.dap')
require("main.plugins.settings.null_ls")

require("main.plugins.settings.telescope")
require("main.plugins.settings.fidget")
