[settings]
cache_prune_age = "7d"
color_theme = "default"
locked = false
locked_verify_provenance = false
lockfile = false
minimum_release_age = "24h"
paranoid = true
verbose = false
status.missing_tools = "always"
status.show_deps_stale = true
status.show_env = true
status.show_tools = true
status.truncate = false
dotfiles.root = "~/projects/.dotfiles"

[env]
MISE_BREW_CASK_OPT_APPDIR = "$HOME/Applications"
_.python.venv = { path = ".venv", create = true }

[bootstrap.macos.dock]
autohide = true
orientation = "bottom"
magnification = true

[bootstrap.brew]
adopt = true

[bootstrap.brew.taps]
"homebrew/cask" = "latest"
"homebrew/core" = "latest"
"homebrew/cask-fonts" = "latest"

[bootstrap.packages]
# Git
"brew:git" = "latest"
"brew:git-lfs" = "latest"
"brew:gh" = "latest"
"brew:gitleaks" = "latest"

# Github related tools
"brew:act" = "latest"
"brew:dependabot" = "latest"

# Bash related tools
"brew:bash" = "latest"
"brew:bash-completion@2" = "latest"
# ZSH related tools
"brew:zsh-autosuggestions" = "latest"
"brew:zsh-syntax-highlighting" = "latest"
"brew:zsh-completions" = "latest"
"brew:starship" = "latest"

# General command-line tools
"brew:fzf" = "latest"
"brew:bat" = "latest"
"brew:fd" = "latest"
"brew:eza" = "latest"
"brew:jless" = "latest"
"brew:shellcheck" = "latest"
"brew:shfmt" = "latest"
"brew:jq" = "latest"
"brew:yq" = "latest"
"brew:httpie" = "latest"
"brew:tree" = "latest"
"brew:wget" = "latest"
"brew:ripgrep" = "latest"
"brew:zoxide" = "latest"
"brew:htop" = "latest"

# Terminal multiplexer
"brew:tmux" = "latest"
"brew:herdr" = "latest"
# Code editor
"brew:neovim" = "latest"
# Kubernetes
"brew:kubernetes-cli" = "latest"
"brew:k9s" = "latest"
"brew:helm" = "latest"
"brew:helmfile" = "latest"
"brew:kubectx" = "latest"
"brew:kind" = "latest"
"brew:popeye" = "latest"
# Load testing tools
"brew:k6" = "latest"
# AI terminal and desktop tools
"brew:opencode" = "latest"
# "brew-cask:chatgpt" = "latest"
"brew-cask:copilot-cli" = "latest"
# "brew:ollama" = "latest"
# "brew-cask:lm-studio" = "latest"
# "brew-cask:claude-code" = "latest"
# "brew-cask:claude" = "latest"
# Fonts
"brew-cask:font-fira-code-nerd-font" = "latest"
"brew-cask:font-jetbrains-mono-nerd-font" = "latest"
# Security tools
"brew:bitwarden-cli" = "latest"
# "brew-cask:1password-cli" = "latest"
"brew:pinentry-mac" = "latest"
"brew:gnupg" = "latest"
"brew:trivy" = "latest"
# "brew-cask:nordlayer" = "latest"
# Productivity tools
"brew-cask:obsidian" = "latest"
# "brew-cask:miro" = "latest"
# "brew-cask:figma" = "latest"
# "brew-cask:meetily" = "latest"

# Communication tools
# "brew-cask:postman" = "latest"
# "brew-cask:slack" = "latest"
"brew-cask:whatsapp" = "latest"
# "brew-cask:zoom" = "latest"
"brew-cask:discord" = "latest"

# Development tools
"brew-cask:docker-desktop" = "latest"
# "brew-cask:pgadmin4" = "latest"
# "brew-cask:iterm2" = "latest"
# "brew-cask:microsoft-azure-storage-explorer" = "latest"
"brew:pre-commit" = "latest"

# Code Editors
"brew-cask:visual-studio-code" = "latest"
# "brew-cask:zed" = "latest"
# "brew-cask:cursor" = "latest"

#Browsers
"brew-cask:google-chrome" = "latest"
# "brew-cask:microsoft-edge" = "latest"

# MacOS Applications
"brew-cask:uhk-agent" = "latest"
"brew-cask:rectangle" = "latest"
"brew-cask:monitorcontrol" = "latest"
# "brew-cask:granola" ="latest"
# "brew:synergy-core" = "latest"
# "brew-cask:raspbery-pi-imager" = "latest"

[dotfiles]
"~/.config/mise" = { source = "~/projects/.dotfiles/config/mise", mode = "symlink" }
"~/.ssh" = { source = "~/projects/.dotfiles/config/.ssh", mode = "symlink" }
"~/.config/git" = { source = "~/projects/.dotfiles/config/git", mode = "symlink" }
"~/.gitconfig*" = { source = "~/projects/.dotfiles/config/.gitconfig*", mode = "symlink" }
"~/.zshenv" = { source = "~/projects/.dotfiles/config/zsh/.zshenv", mode = "symlink" }
"~/.config/zsh" = { source = "~/projects/.dotfiles/config/zsh", mode = "symlink" }
"~/Library/Application Support/Code/User/*.json" = { source = "~/projects/.dotfiles/vscode/*.json", mode = "symlink" }
"~/.config/opencode" = { source = "~/projects/.dotfiles/config/opencode", mode = "symlink" }
"~/.config/starship.toml" = { source = "~/projects/.dotfiles/config/starship.toml", mode = "symlink" }
"~/.config/nvim" = { source = "~/projects/.dotfiles/config/nvim", mode = "symlink" }
"~/.tmux.conf" = { source = "~/projects/.dotfiles/config/.tmux.conf", mode = "symlink" }

[tools]
# Programming languages
python = ["3.12","3.13","3.14"]
node = ["22", "lts"]
go = "latest"
rust = "latest"
# Python
uv = { version = "latest", depends = [
  "python",
] } # Universal virtual environment manager
poetry = { version = "latest", depends = [
  "python",
] } # Python dependency management and packaging

[shell_alias]
# file management
l = 'eza'
ll = 'eza -lA -F always --icons=always -s type'
la = 'll'
tree = 'l --tree'
'..' = 'cd ..'
'...' = 'cd ../..'
'....' = 'cd ../../..'

# git
g = 'git'
gs = 'git status'
gp = 'git pull'
gfa = 'git fetch --all --prune --verbose'
gc = 'git commit'
gca = 'git commit -a'
gco = 'git checkout'
gb = 'git branch'
gd = 'git diff'
gl = 'git log --oneline --graph --decorate'
gla = 'git log --oneline --graph --decorate --all'

# uv
py = 'uv run python'
pytest = 'uv run pytest'
uvr = 'uv run'
uvsync = 'uv sync'
uvlock = 'uv lock'

# kubernetes
k = 'kubectl'

# misc
cat = 'bat'
grep = 'rg'
find = 'fd'


[tasks.docker-sysclean]
description = "Clean up Docker system"
run = "docker system prune -af --volumes"
